version: '3.1'

services:
  mcaptcha:
    image: mcaptcha/mcaptcha-dos-server:latest
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres # set password at placeholder
      MCAPTCHA_REDIS_URL: redis://mcaptcha-redis/
      MCAPTCHA_CAPTCHA_SITEKEY: "29UeO6rJCB5knsCKdYbF02hpA6AcwFqq"
      RUST_LOG: debug

  postgres:
    image: postgres:13.2
    volumes:
      - mcaptcha-dos-data:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: password # change password
      PGDATA: /var/lib/postgresql/data/mcaptcha/

volumes:
  mcaptcha-dos-data:
